language: php

sudo: false

php: [7.1, 7.2]

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer update --no-interaction --prefer-source

script:
  - bin/phpspec run --no-interaction --format=pretty
